requires = ["tox>=4.22"]
env_list = ["fix"]
skip_missing_interpreters = true

[env.fix]
description = "format the code base to adhere to our styles, and complain about what we cannot do automatically"
skip_install = true
deps = ["pre-commit-uv>=4.1.3"]
pass_env = [{ replace = "ref", of = ["env_run_base", "pass_env"], extend = true }, "PROGRAMDATA"]
commands = [["pre-commit", "run", "--all-files", "--show-diff-on-failure", { replace = "posargs", extend = true }]]

[env.dev]
package = "skip"
description = "dev environment"
deps = ["pytest>=8.3.3", "-e pyproject-fmt"]
commands = [["uv", "pip", "tree"], ["python", "-c", 'print(r"{env_python}")']]
